name: flutter_image_saver
description: Simple and effective cross platform image saver for flutter, supported web and desktop.
version: 0.2.1
homepage: https://github.com/qiuxiang/flutter_image_saver

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.3.1+5
  path_provider: ">=2.0.0"
  permission_handler: ">=6.0.0"
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: qiuxiang.flutter.flutter_image_saver
        pluginClass: FlutterImageSaverPlugin
      ios:
        pluginClass: FlutterImageSaverPlugin
